// Copyright (C) 2019, 2020  Keyboard.io, Inc
//
// this is the style you want to emulate.
// This is the canonical layout file for the Quantum project. If you want to add another keyboard,

#include QMK_KEYBOARD_H

enum layer_names {
    _QW,
    _RS,
    _LW,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = LAYOUT(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, LSFT_T(KC_A), KC_S, KC_D, LALT_T(KC_F), KC_G, KC_H, KC_J, KC_K, KC_L, RSFT_T(KC_SCLN), KC_Z, LGUI_T(KC_X), LGUI_T(KC_C), LGUI_T(KC_V), KC_B, KC_TAB, KC_ENT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_SPC, TG(2), TG(1), KC_BSPC, KC_DEL, KC_MINS, KC_QUOT, KC_NO),
  [1] = LAYOUT(KC_ESC, KC_NO, KC_MS_U, KC_BTN1, KC_BTN2, KC_NO, KC_FIND, KC_UP, KC_NO, KC_UNDO, KC_DEL, KC_MS_L, KC_MS_D, KC_MS_R, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_AGIN, KC_CAPS, KC_PGDN, KC_NO, KC_NO, KC_NO, KC_NO, MO(3), KC_WH_U, KC_CUT, KC_COPY, KC_PSTE, KC_NO, KC_LSFT, KC_LCTL, KC_LALT, KC_LGUI, KC_SPC, KC_NO, TO(0), KC_WH_D, KC_NO, KC_NO, KC_NO, KC_NO),
  [2] = LAYOUT(KC_LBRC, KC_RBRC, KC_SLSH, KC_BSLS, KC_GRV, KC_COMM, KC_DOT, KC_SCLN, KC_MINS, KC_EQL, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_LSFT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_CUT, KC_COPY, KC_UP, KC_PSTE, KC_RSFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TO(0), KC_NO, KC_LEFT, KC_DOWN, KC_RGHT, KC_NO),
  [3] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLD, KC_VOLU, KC_MPLY, KC_MNXT, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MSTP, KC_MPRV, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};